app:
  author: 张一风
  debug: true
  description: 一个开源且跨平台的博客同步工具
  epilog: 请使用 -h 查看帮助信息
  name: PosySync
  version: 1.0.0
data:
  executable:
    path: C:\Program Files\Google\Chrome\Application\chrome.exe
  path: D:\Documents\PostSync
  posts:
    path: C:\Users\xiaof\Desktop
  storage:
    path: D:\Documents\PostSync\data\storage.json
  webview:
    path: D:\Documents\PostSync\webview
default:
  author: 张一风
  category: 后端
  columns:
  - Python文章
  - Java文章
  community:
    bilibili:
      category: 科技
      columns:
      - Python文章
      cover: null
      tags: Python
      timeout: 40000
      topic: 编程
    cnblog:
      category: Python
      columns:
      - Python文章
      cover: null
      tags:
      - Python
      timeout: 20000
      topic: null
    csdn:
      category: null
      columns:
      - Python文章
      cover: null
      tags:
      - Python
      timeout: 20000
      topic: 知识
    juejin:
      category: 后端
      columns:
      - Python文章
      cover: null
      tags:
      - Python
      timeout: 40000
      topic: 知识
    wechat:
      category: 后端
      columns:
      - PHP文章
      cover: null
      tags: python
      timeout: 20000
      topic: null
    wordpress:
      category: null
      columns: null
      cover: null
      tags:
      - Python
      timeout: 40000
      topic: null
    zhihu:
      category: Python
      columns:
      - Python
      cover: null
      tags: Python
      timeout: 20000
      topic: null
  cover: static/imgs/default-cover.png
  devtools: false
  digest:
    length: 100
  headless: false
  no_viewport: true
  tags:
  - Python
  timeout: 40000
  topic: 知识
  url: null
  user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/128.0.0.0 Safari/537.36
view:
  height: 860
  width: 1440
wordpress:
  domain: yunyicloud.cn
  enable: true
  url: https://yunyicloud.cn
