app:
  author: 张一风
  debug: true
  description: 一个开源且跨平台的博客同步工具
  epilog: 请使用 -h 查看帮助信息
  name: PosySync
  version: 1.0.0
data:
  executable:
    path: C:\Program Files\Google\Chrome\Application\chrome.exe
  path: D:\Documents\PostSync
  posts:
    path: D:\Documents\PostSync\posts
  storage:
    path: D:\Documents\PostSync\storage.json
  webview:
    path: D:\Documents\PostSync\webview
  temp:
    path: D:\Documents\PostSync\temp
  log:
    path: D:\Documents\PostSync\log
default:
  author: 张一风
  category:
  columns:
  -
  community:
    bilibili:
      category: 科技
      columns:
      -
      cover:
      tags:
      timeout: 40000
      topic:
    cnblog:
      category: Python
      columns:
      -
      cover: null
      tags:
      -
      timeout: 20000
      topic:
    csdn:
      category:
      columns:
      -
      cover:
      tags:
      -
      timeout: 20000
      topic:
    juejin:
      category:
      columns:
      -
      cover: null
      tags:
      -
      timeout: 40000
      topic:
    wechat:
      category:
      columns:
      -
      cover:
      tags:
      timeout: 20000
      topic:
    wordpress:
      category: null
      columns: null
      cover: null
      tags:
      -
      timeout: 40000
      topic: null
    zhihu:
      category:
      columns:
      -
      cover: null
      tags:
      timeout: 20000
      topic: null
  cover: static/imgs/default-cover.png
  devtools: false
  digest:
    length: 100
  headless: true
  no_viewport: false
  tags:
  -
  timeout: 40000
  topic:
  url: null
  user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/128.0.0.0 Safari/537.36
view:
  height: 860
  width: 1440
wordpress:
  domain: yunyicloud.cn
  enable: true
  url: https://yunyicloud.cn
