app:
  name: PosySync
  description: 一个开源的跨平台的博客同步工具
  version: 1.0.0
  author: 张一风
  epilog: 请使用 -h 查看帮助信息
  debug: True  # 是否开启调试模式
view:
  width: 1920
  height: 1080

data:
  user:
    dir: C:\Users\xiaof\AppData\Local\Google\Chrome\User Data  # 浏览器用户数据目录

wordpress:
  enable: True  # 是否启用WordPress同步
  url: https://yunyicloud.cn  # WordPress博客地址

default:
  author: 张一风
  devtools: False  # 是否打开浏览器调试工具
  headless: False  # 是否后台运行浏览器
  browser: chrome  # 选择使用的浏览器 (msedge,chrome,firefox)
  no_viewport: False  # 是否全屏
  cover: static/imgs/default-cover.png  # 默认封面图片
  tags:
    - python
  url:  # 默认博客连接
  times: 3 # 错误重试次数
  timeout: 1000  # 请求超时时间
  category: 后端  # 默认分类
  topic: 知识  # 默认话题
  columns:
    - 解决
  digest:
    length: 100
  community:
    juejin:
      category: 后端
      tags: python
      columns:
        - PHP文章
      cover:
    csdn:
      category: 后端
      cover:
      tags: python
      columns:
        - PHP文章
    zhihu:
      category: 后端
      tags: python
      columns: 解决
      cover:
    wechat:
      category: 后端
      tags: python
      columns: 解决
      cover:
    cnblog:
      category: 后端
      tags:
        - python
        - test
      columns: 解决
      cover:
    wordpress:
      category: 后端
      tags: python
      columns: 解决
      cover: