app:
  name: PosySync
  description: 一个开源且跨平台的博客同步工具
  version: 1.0.0
  author: 张一风
  epilog: 请使用 -h 查看帮助信息
  debug: False  # 是否开启调试模式
view:
  width: 1920
  height: 1080

data:
  user:
    dir: C:\Users\xiaof\AppData\Local\Microsoft\Edge\User Data  # 浏览器用户数据目录
  executable:
    path: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe  # 浏览器可执行文件路径

wordpress:
  enable: True  # 是否启用WordPress同步
  url: https://yunyicloud.cn  # WordPress博客地址

default:
  author: 张一风
  devtools: False  # 是否打开浏览器调试工具
  headless: True  # 是否后台运行浏览器
  browser: msedge  # 选择使用的浏览器 (msedge,chrome,firefox)
  no_viewport: False  # 是否全屏
  cover: static/imgs/default-cover.png  # 默认封面图片
  tags:
    - Python
  url:  # 默认博客连接
  timeout: 10000  # 请求超时时间
  category: 后端  # 默认分类
  topic: 知识  # 默认话题
  columns:
    - Python文章
  digest:
    length: 100
  community:
    juejin:
      category: 后端
      tags:
        - Python
      columns:
        - Python文章
      cover:
      topic: 知识
    csdn:
      category:
      tags:
        - Python
      columns:
        - Python文章
      cover:
      topic: 知识
    zhihu:
      category: Python
      tags: Python
      columns:
        - Python
      cover:
      topic:
    wechat:
      category: 后端
      tags: python
      columns:
        - PHP文章
      cover:
      topic:
    cnblog:
      category: Python
      tags:
        - Python
      columns:
        - Python文章
      cover:
      topic:
    wordpress:
      category:
      tags:
        - Python
      columns:
      cover:
      topic:
    bilibili:
      category: 科技
      tags: Python
      columns:
        - Python文章
      cover:
      topic: 编程