app:
  debug: true
  desc: 软件设置
data:
  desc: 软件数据目录
  executable:
    desc: 可执行程序路径
    path: C:\Program Files\Google\Chrome\Application\chrome.exe
  log:
    desc: 日志文件目录
    path: D:\Documents\PostSync\log
  path: D:\Documents\PostSync
  posts:
    desc: 文章目录
    path: D:\Documents\PostSync\posts
  states:
    desc: 登录状态文件
    path: D:\Documents\PostSync\login_state.json
  storage:
    desc: 软件数据存储文件
    path: D:\Documents\PostSync\storage.json
  temp:
    desc: 临时文件目录
    path: D:\Documents\PostSync\temp
  webview:
    desc: 软件视图存放目录
    path: D:\Documents\PostSync\webview
default:
  author: 张一风
  category: Python
  columns:
  - Python
  community:
    bilibili:
      category: 科技
      columns:
      - Python
      cover: null
      desc: 哔哩哔哩
      tags: []
      timeout: 40000
      topic: null
    cnblog:
      category: Python
      columns:
      - Python
      cover: null
      desc: 博客园
      tags: []
      timeout: 20000
      topic: null
    csdn:
      category: Python
      columns:
      - 解决问题
      cover: null
      desc: CSDN
      tags: []
      timeout: 20000
      topic: null
    juejin:
      category: null
      columns: []
      cover: null
      desc: 掘金
      tags: []
      timeout: 40000
      topic: null
    wechat:
      category: null
      columns: []
      cover: null
      desc: 微信公众号
      tags: []
      timeout: 20000
      topic: null
    zhihu:
      category: null
      columns: []
      cover: null
      desc: 知乎
      tags: []
      timeout: 20000
      topic: null
  cover: static/imgs/default-cover.png
  desc: 默认设置
  devtools: false
  digest:
    desc: 文章摘要
    length: 100
  headless: false
  no_viewport: false
  tags:
  - Python
  timeout: 40000
  topic: null
  url: null
  user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/128.0.0.0 Safari/537.36
view:
  desc: 软件视图设置
  height: 860
  width: 1440
